name: Executar save_data.py todo dia à meia-noite

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  run-save-data:
    name: Executar script save_data.py
    runs-on: ubuntu-latest

    env:
      PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      FIREBASE_CREDENTIALS_PATH: ${{ secrets.FIREBASE_CREDENTIALS_PATH }}

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar arquivo .env
        run: |
          echo "PLAYLIST_ID=$PLAYLIST_ID" >> .env
          echo "YOUTUBE_API_KEY=$YOUTUBE_API_KEY" >> .env
          echo "FIREBASE_CREDENTIALS_PATH=$FIREBASE_CREDENTIALS_PATH" >> .env

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv google-api-python-client google-cloud-firestore plotly pytz

      - name: Executar backend/save_data.py
        run: |
          python backend/save_data.py
